### ISSUE TITLE
redis.so: undefined symbol: igbinary_serialize in Unknown on line 0

### ISSUE THREAD

**Issue by daisyxchen** [litespeedtech/ols1clk#10]
PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/redis.so' - /usr/lib64/php/modules/redis.so: undefined symbol: igbinary_unserialize in Unknown on line 0

PHP 5.3.3 (fpm-fcgi) (built: Mar 22 2017 12:28:05)
CentOS 6.5
Redis redis-cli 3.2.3

**Comment by jacksonlst** [comment]
Does not look like ols1clk related since it won't install php 5.3.3. Also PHP 5.3.3 (fpm-fcgi)  is for apache. LiteSpeed will use lsphp.   ols1clk doesn't seem to install Redis either.  

You should check the package provider for the redis module.
