### ISSUE TITLE
not set -w not install mysql 

### ISSUE THREAD

**Issue by jiid** [litespeedtech/ols1clk#15]
I just install php mysql with my code,but not set ` --wordpress ` will not install mysql
`bash <( curl -k https://raw.githubusercontent.com/litespeedtech/ols1clk/master/ols1clk.sh )  --email admin@xx.xx --lsphp 72 --mariadbver 10.1`

**Comment by litespeedtech** [comment]
Yes.
Mysql only will be installed while with wordpress, and it need to be tested with wordpress pages fater installed.

**Comment by litespeedtech** [comment]
Answered. Close the issue now.
