### ISSUE TITLE
"Your PHP installation appears to be missing the MySQL extension which is required by WordPress."

### ISSUE THREAD

**Issue by Sykat** [litespeedtech/ols1clk#16]
I have installed it with Wordpress and this is the error when I try to access the site via IP.
`wget --no-check-certificate https://raw.githubusercontent.com/litespeedtech/ols1clk/master/ols1clk.sh && bash ols1clk.sh -a ***** -e *****@gmail.com --lsphp 70 -w --wordpresspath /var/www/***** -r ***** --dbname ***** --dbuser ***** --dbpassword ***** --wpuser ***** --wppassword *****`
***** are personal informations so I removed them.

**Comment by litespeedtech** [comment]
Usually you need to use domain to access your wordpress site. Because in the Vhost/listener mapping, we use the domain, but not a *.
This is a right case.
