### ISSUE TITLE
Update php version to lsphp80

### ISSUE THREAD

**Issue by SummerAfternoon** [litespeedtech/ols1clk#32]
I have noticed that lsphp80 has supported lsphp80-memcached. So can you update the script?

**Comment by Code-Egg** [comment]
HI, I'm working on it, will push a new version to support PHP 8 before next monday

**Comment by Code-Egg** [comment]
Hi @SummerAfternoon,
I just pushed which has lsphp 80 supported, feel free to give it a try.
