### ISSUE TITLE
aNY nEW uPDATE cOMING OR ?

### ISSUE THREAD

**Issue by pecker99956** [litespeedtech/ols1clk#35]
Just checking..
Any procedure to add SSL or ?

**Comment by Code-Egg** [comment]
If you want to set up Let's Encrypt certificate, you can follow https://openlitespeed.org/kb/lets-encrypt-ssl-on-openlitespeed/ .
If you have your own certificate, can start from the "Configure OpenLiteSpeed for SSL" section.
