### ISSUE TITLE
help me 

### ISSUE THREAD

**Issue by jarodvip** [litespeedtech/ols1clk#38]
Start OpenLiteSpeed one click installation >> >> >> >> >> >> >>
System update
Start setup OpenLiteSpeed
     - add litespeedtech repo
     - update list
E: Malformed entry 1 in list file /etc/apt/sources.list.d/lst_debian_repo.list (Component)
E: The list of sources could not be read.
     - Install OpenLiteSpeed
An error occured during OpenLiteSpeed installation.
     - Install lsphp73
An error occured during lsphp73 installation.
     - Setup lsphp symlink
End setup OpenLiteSpeed
ols1clk.sh: line 623: /usr/local/lsws/password: No such file or directory
ols1clk.sh: line 1033: /usr/local/lsws/admin/fcgi-bin/admin_php: No such file or directory
mv: cannot move 'example.key' to '/usr/local/lsws/conf/example.key': No such file or directory
mv: cannot move 'example.crt' to '/usr/local/lsws/conf/example.crt': No such file or directory
chmod: cannot access '/usr/local/lsws/conf/example.key': No such file or directory
chmod: cannot access '/usr/local/lsws/conf/example.crt': No such file or directory
WP CLI already exist
Start setup virtual host config
/usr/local/lsws/conf/httpd_config.conf is missing. It appears that something went wrong during OpenLiteSpeed installation.
ols1clk.sh: line 1154: /usr/local/lsws/PLAT: No such file or directory
End setup virtual host config
Avoid port 80/443 conflict.
Start Install MariaDB
     - Install software properties
     - Add MariaDB repo
     - Update packages
E: Malformed entry 1 in list file /etc/apt/sources.list.d/lst_debian_repo.list (Component)
E: Malformed entry 1 in list file /etc/apt/sources.list.d/mariadb_repo.list (Component)
E: The list of sources could not be read.
     - Install MariaDB
An error occured during installation of MariaDB. Please fix this error and try again.
You may want to manually run the command 'apt-get -y -f --allow-unauthenticated install mariadb-server' to check. Aborting installation!

**Comment by Code-Egg** [comment]
May I know the system information? 
```
cat /etc/os-release
```
and 
```
lscpu | grep Model
```
and what's the whole command you used to install? 
Also, it seems even MariaDB is failed to install, may I know if you can install any packages? e.g. 
```
apt-get install net-tools
```
