### ISSUE TITLE
MariaDB ins't installed with one click command

### ISSUE THREAD

**Issue by droplinxuser** [litespeedtech/ols1clk#41]
Using Ubuntu 20.04 from Hetzner Cloud.
My command:

```
./ols1clk.sh \
--adminpassword 1234 \
--email 0@gmail.com \
--lsphp 80 \
--mariadbver 10.6 \
--dbrootpassword 5678
```

**Comment by droplinxuser** [comment]
Okay so it's expected unfortunately :|
https://github.com/litespeedtech/ols1clk/issues/15

Closed.

**Comment by Code-Egg** [comment]
@droplinxuser  
Actually, it's supported, please add `--pure-mariadb`  parameter.
