### ISSUE TITLE
./vhsetup.sh php: command not found

### ISSUE THREAD

**Issue by droplinxuser** [litespeedtech/ols1clk#42]
Using Ubuntu 20.04 on Hetzner Cloud
Just after I install with ./ols1clk.sh

My command:
```
./vhsetup.sh -d site.com
./vhsetup.sh: line 139: php: command not found
./vhsetup.sh: line 140: php: command not found
Vhost created success!
Setup finished!

```

**Comment by Code-Egg** [comment]
Fixed with the latest commit https://github.com/litespeedtech/ols1clk/commit/3a13354a9e9ff72b3c02710dfa2ad790909a5d9b, feel free to give it a try

**Comment by droplinxuser** [comment]
Works great now, thank you.
And it comes with PHP 8.1 now :)

**Comment by Code-Egg** [comment]
Great
