### ISSUE TITLE
Can I specify "--key-type ecdsa"?

### ISSUE THREAD

**Issue by droplinxuser** [litespeedtech/ols1clk#43]
With the new vhost command:
`./vhsetup.sh -d example.com -le xxx@gmail.com -f`

How can I specify to use (--key-type ecdsa) Certificate?

**Comment by Code-Egg** [comment]
It's not supported. If you only have a few domains, can manually apply the cert with the certbot command with the parameters you need. 
 e.g. 
```
./vhsetup.sh -d example.com
certbot certonly --non-interactive --agree-tos --key-type ecdsa -m example@example.com --webroot -w /var/www/xxx -d example.com
```
or download the [script](https://github.com/litespeedtech/ls-cloud-image/blob/master/Setup/domainsetup.sh)  and custom the [certbot command](https://github.com/litespeedtech/ls-cloud-image/blob/master/Setup/domainsetup.sh#L242-L244).

**Comment by Code-Egg** [comment]
1. Correct 
2. The domainsetup.sh script is mainly for the cloud image user's first-time setup only. Then they will need to use vhsetup.sh for the rest virtual host setup.
