### ISSUE TITLE
Upgrade OS From  Ubuntu 20.04 (LTS) x64 to  Ubuntu 22.04 (LTS) x64

### ISSUE THREAD

**Issue by sufiaakter19** [litespeedtech/ols1clk#47]
Upgrade OS From  Ubuntu 20.04 (LTS) x64 to  Ubuntu 22.04 (LTS) x64 on
https://marketplace.digitalocean.com/apps/openlitespeed-wordpress

**Comment by Code-Egg** [comment]
Upgraded
