### ISSUE TITLE
instructions ols1clk

### ISSUE THREAD

**Issue by devrob20** [litespeedtech/ols1clk#53]
thank you for such detailed instructions, but shouldnt the ols1clk be like

docker exec -it <your ols container (btw set a container name in setup)> bash curl -sk https://raw.githubusercontent.com/litespeedtech/ls-cloud-image/master/Setup/vhsetup.sh ) -d www.example.com -w

or do you need to run it on the host ?

**Comment by Code-Egg** [comment]
No problem. Those projects can not be mixed together. 

https://raw.githubusercontent.com/litespeedtech/ls-cloud-image/master/Setup/vhsetup.sh is for ls-cloud-image 

For docker, it's a different project(https://github.com/litespeedtech/ols-docker-env).
Check https://github.com/litespeedtech/ols-docker-env#creating-a-domain-and-virtual-host if you want to create an additional virtual host in the docker env.
