### ISSUE TITLE
One Click Install fails

### ISSUE THREAD

**Issue by smileBeda** [litespeedtech/ols1clk#54]
Following https://openlitespeed.org/kb/1-click-install/

It says to run `bash <( curl -k https://raw.githubusercontent.com/litespeedtech/ols1clk/master/ols1clk.sh )`
On both Ubuntu 20 and 22, it throws a `curl: option -k https://raw.githubusercontent.com/litespeedtech/ols1clk/master/ols1clk.sh: is unknown`

cURLing without the `-k` (which afaik just stands for ignoring the LTS cert) works.

Not sure why, but it could be that some other users run into this, and doing the commando without `-k` or `--insecure` works. With either throws `curl: option -k https://raw.githubusercontent.com/litespeedtech/ols1clk/master/ols1clk.sh: is unknown`

**Comment by Code-Egg** [comment]
Thanks for sharing, that option is a basic feature and curl should support it on all platforms. May I know which curl version you have on the Ubuntu system? Also, if you run `curl --help all`, does it has " -k, --insecure" included?

**Comment by smileBeda** [comment]
That was on a (fresh) Ubuntu 20 install, I scrapped it and did an Ubuntu 22 install.. which worked with the suggested command 🤷 
I recall I did run the help command, and no, the k/insecure was not included. But, I saw it is available of course on the official man page of cURL itself ...
