### ISSUE TITLE
Installion of MariaDB fails

### ISSUE THREAD

**Issue by dhiraj969371** [litespeedtech/ols1clk#55]
OS: Ubuntu 22.04 (Jammy)
Server Type: Dedicated Server

While installing MariaDB the script fails.

"You may want to manually run the command 'apt-get -y -f --allow-unauthenticated install mariadb-server' to check. Aborting installation!"

I suspect this happens because the web location of the repo (example on line 828 of the script) currently does not exist. MariaDB may have updated the location of the repo.

Possible solution: Update the web location of the repo in the script.

**Comment by Code-Egg** [comment]
Hi @dhiraj969371 
I just checked the repo and it does exist, see http://mirror.mariadb.org/repo/10.9/ubuntu/dists/jammy/main/, also, the setup test works on a fresh Ubuntu 22.04 server. Could you try it again, if it's still not working, please share the output of the`/etc/apt/sources.list.d/mariadb.list` and `apt update && apt-get install mariadb-server` results.

**Comment by dhiraj969371** [comment]
Try and install it with these parameters:
PHP: 7.4
MariaDB: 10.6

Also specify an email, root DB password and a webadmin password in the script execution command.

I tried to install it multiple times on Hetzner AX41 and it shows that same error on clean installs. What's weird is that it installed correctly 3 days ago and a month ago. But doesn't work now. Also if possible do an apt update and apt upgrade before executing the script. Maybe some update is messing with the install.

**Comment by dhiraj969371** [comment]
> Hi @dhiraj969371 I just checked the repo and it does exist, see http://mirror.mariadb.org/repo/10.9/ubuntu/dists/jammy/main/, also, the setup test works on a fresh Ubuntu 22.04 server. Could you try it again, if it's still not working, please share the output of the`/etc/apt/sources.list.d/mariadb.list` and `apt update && apt-get install mariadb-server` results.

I will get that for you in about 8 hours.

**Comment by Code-Egg** [comment]
HI @dhiraj969371 
Any luck?
