### ISSUE TITLE
Add support for Percona Server for MySQL 

### ISSUE THREAD

**Issue by peixotorms** [litespeedtech/ols1clk#57]
While MySQL and MariaDB are great, I (personally) find that Percona usually performs better for high concurrency.
I would like to suggest including it as an alternative on the ols1clk script, as it's basically a drop off replacement like MariaDB.
`https://docs.percona.com/percona-server/8.0/installation.html`

**Comment by Code-Egg** [comment]
Done, the changes have been pushed in the [commit](https://github.com/litespeedtech/ols1clk/commit/d2b6cec038ac9c06c815a1e2d4597b4317e508cf)
Feel free to give it a try.

**Comment by peixotorms** [comment]
Thanks, working!

**Comment by Code-Egg** [comment]
Good to know it works.
