### ISSUE TITLE
Some tips

### ISSUE THREAD

**Issue by xiaomubiao** [litespeedtech/ols1clk#6]
1、hope can  choose  the  mysql version  and  install  path.
2、support  jemalloc
3、support letsencrypt
Thanks!

**Comment by daganyaakov** [comment]
In most cases the `ledencrypt` is implemented after a full domain redirection setting so it seems to me less necessary for an initial automatic installation

**Comment by ivmm** [comment]
@xiaomubiao 
1. Add mariadb-server Multi-version support on https://github.com/litespeedtech/ols1clk/pull/8
2.Unless your server has very lots of memory and CPU cores, the jemalloc effect is very weak
3.Letsencrypt can be achieved by using tools: Acme.sh
