### ISSUE TITLE
Make DB packages optional or skippable

### ISSUE THREAD

**Issue by peixotorms** [litespeedtech/ols1clk#60]
Hi,

Can you please modify the ols1clk script to have some sort of flag to skip installation of MySQL/MariaDB/Percona?

There are cases where we may want to setup OLS but skip installing the database server, for example, when using with a remote server like AWS RDS.

Thank you

**Comment by Code-Egg** [comment]
Hi,
I think it's already supported, just run the command without WordPress installation. E.g. `./ols1clk.sh`

**Comment by peixotorms** [comment]
Hi, 

When I run for example: 
`/home/scripts/ols1clk.sh --adminpassword myadminuser --adminpassword myadminpass --email noreply@example.local --lsphp 80`

I can confirm that it does not install a database server, thank you.
However, it shows a default MariaDB version: `https://i.imgur.com/lYgTzKj.png`
I think that you should remove it, as it appears to be ready to install it.

Also regarding that info... the WebAdmin URL: is missing.
Perhaps adding it as https://ipaddress:7080 would be better for completion.
If you want to improve it further, customizing the port with `--adminport` would be even better (for security).

---

One last thing is that on Vultr specifically (didn't check others), new instances default with ufw installed and allowing with only ssh port open on Ubuntu 22.04.

I understand that we still need to manually open ports for any web server to work... but perhaps a quick check to see if ufw is installed and printing a small notice warning which ports need to be open for it to work, can be an improvement.
Not very important, but good as improvement.

Thank you

**Comment by Code-Egg** [comment]
Ok, fixed the following. 
1. add `--adminport` 
2. fix MariaDB version display
3. Add WebAdmin URL in display

Firewall detection may not easy, skip it for now.

**Comment by peixotorms** [comment]
Great, thank you for the changes.
