### ISSUE TITLE
Allow different "admin" user

### ISSUE THREAD

**Issue by peixotorms** [litespeedtech/ols1clk#61]
Hi,

Not sure if this is possible, but since we already have a `--adminpassword` flag, can we also please have a `--adminuser` as well?
The goal if possible, is not to create the "admin" username at all, and instead use our own admin username.

Thank you

**Comment by Code-Egg** [comment]
Done, the changes have been pushed in the [commit](https://github.com/litespeedtech/ols1clk/commit/a07252533303d86adee20bb915ef31a5fdeafb69)
Feel free to give it a try.

**Comment by peixotorms** [comment]
Thanks, this works great!
