### ISSUE TITLE
add missing php packages

### ISSUE THREAD

**Issue by peixotorms** [litespeedtech/ols1clk#62]
Hi there,

By default, I see that on debian it installs these packages:

`silent ${APT} -y install $action lsphp$LSPHPVER lsphp$LSPHPVER-mysql lsphp$LSPHPVER-imap lsphp$LSPHPVER-curl
`

Please add other missing packages, as some are required by certain plugins on wordpress:

`silent ${APT} -y install $action lsphp$LSPHPVER lsphp$LSPHPVER-mysql lsphp$LSPHPVER-imap lsphp$LSPHPVER-curl lsphp$LSPHPVER-imagick lsphp$LSPHPVER-intl lsphp$LSPHPVER-memcached lsphp$LSPHPVER-opcache lsphp$LSPHPVER-redis
`

The same for centos as well.

---

Also probably out of scope... but in the future would be great to have the option to install php-fpm in addition to lsphp, and use it for virtual hosts.

Thank you

**Comment by qtwrk** [comment]
some of these extensions are built-in into the main package ,  I would suggest to check via phpinfo()

**Comment by dhiraj969371** [comment]
This one is an issue for me as well since WP site health mentions it in every scan if I don't install the missing packages

**Comment by Code-Egg** [comment]
Hi @dhiraj969371 
I just checked my site, no warning. So, could you help to narrow it down to one extension so we can help to add it as default? And which PHP version you are testing with?

**Comment by dhiraj969371** [comment]
> Hi @dhiraj969371 I just checked my site, no warning. So, could you help to narrow it down to one extension so we can help to add it as default? And which PHP version you are testing with?

It happens when I only have LSPHP 7.4 on my system. I haven't tested other LSPHP versions

**Comment by Code-Egg** [comment]
Ok done in the [latest commit](https://github.com/litespeedtech/ols1clk/commit/db537b47c66a35a331ed47e9112cf9a19fdc776e). Feel free to give it a try.
