### ISSUE TITLE
[Feature Request] Support for MariaDB 10.11

### ISSUE THREAD

**Issue by dhiraj969371** [litespeedtech/ols1clk#63]
Since MariaDB 10.11 is officially a LTS version now and recommended on the WP system requirements, it would be nice to have this version supported over 10.9 as the default version of the script

**Comment by Code-Egg** [comment]
thx, latest [commit](https://github.com/litespeedtech/ols1clk/commit/a47f7929444e704d8068092357a7c1b2f640ac0c) has the version included
