### ISSUE TITLE
Multiple issues and requests

### ISSUE THREAD

**Issue by dhiraj969371** [litespeedtech/ols1clk#64]
1: Installing Certbot by default
The readme mentions installing Certbot to use '-le' on "vhsetup.sh". It would be better to install it by default with ols1clk.sh

2: Restarting LSWS
The function "restart_lsws" does "systemctl stop lsws" and "systemctl start lsws". This is a problem specifically for Production servers where stopping the webserver can cause issues if the webserver is processing some request. AFAIK "systemctl restart lsws" does a graceful restart without any downtime and it does the same thing as stopping and starting the service. This is also an issue on vhsetup.sh where it adds an extra command "${LSDIR}/bin/lswsctrl stop" including the ones above. "systemctl restart lsws" is just plain better. The "current restart_lsws" function on both the scripts also creates a problem where if I use WP-CLI right after using the script(s), the WordPress site just goes into "ERR TOO MANY REDIRECTS" mode permanently

Ref: https://openlitespeed.org/kb/command-references-for-administration/

3: Default PHP.ini values too low
I run the below commands to increase some values of PHP that are recommended by most WordPress themes and plugins

sed -i 's|memory_limit = 128M|memory_limit = 256M|g' ${PHP_INI_LOCATION}
sed -i 's|max_execution_time = 30|max_execution_time = 120|g' ${PHP_INI_LOCATION}
sed -i 's|max_input_time = 60|max_input_time = 120|g' ${PHP_INI_LOCATION}
sed -i 's|;max_input_vars = 1000|max_input_vars = 10000|g' ${PHP_INI_LOCATION}
sed -i 's|post_max_size = 8M|post_max_size = 16M|g' ${PHP_INI_LOCATION}
sed -i 's|upload_max_filesize = 2M|upload_max_filesize = 16M|g' ${PHP_INI_LOCATION}

4: Installing an object cache by default
Since LSCACHE plugin already has object cache functionality it would be better to just install redis/keydb (2x faster redis implementation) by default

5: Installing Postfix by default since email is a big part of Wordpress

6: SSL fails to install when using Cloudflare (vhsetup.sh)
When the proxy is on in Cloudflare DNS it fails because it is trying to find "Litespeed" in the headers. This is an easy fix.

7: Allow a user to install Woocommerce from the script itself

8: Allow a user to delete useless themes and plugins by default

I can create PRs for all of this on vhsetup.sh if you want but it will take some time. And it would be amazing if there is a consumer friendly version of this like WordOps or EasyEngine but for OLS

**Comment by Code-Egg** [comment]
HI,
For item 1,3,4,5, those are supported in `[cloud-image-build script ](https://github.com/litespeedtech/ls-cloud-image/wiki/Build-WordPress-Image)`actually. Feel free to give it a try. 
Item 2 has been included. I will include item 6 as well. 
I am not sure about items 7 and 8, are those useful?

**Comment by dhiraj969371** [comment]
> HI, For item 1,3,4,5, those are supported in `[cloud-image-build script ](https://github.com/litespeedtech/ls-cloud-image/wiki/Build-WordPress-Image)`actually. Feel free to give it a try. Item 2 has been included. I will include item 6 as well. I am not sure about items 7 and 8, are those useful?

The other scripts you mention are just not what I want. As I see it ols1clk + vhsetup.sh just looks better. Other scripts look worse where they don't use wp-cli or include CyberPanel or isn't for a Dedicated server

7 and 8 are just good to haves where it saves like 2 minutes of time but yeah its optional.

Additional context for 6: Certbot places ".acme_challenge" somewhere in the webroot but when Lets Encrypt checks for the file from their servers it fails because Encryption Mode "Full (Strict)" or "Full" is on. This can be fixed by telling the user to turn the Encryption Mode to "Off" temporarily. The "verify_domain" function has other problems because if it sees that I don't have "Litespeed" in my headers, it just skips the SSL part. And when using Cloudflare the site always has "Cloudflare" instead of "Litespeed"

I will create a fork with the things I think would make more it consumer friendly. I will notify you if you want to integrate some of it.

**Comment by Code-Egg** [comment]
Hi @dhiraj969371, 
Items 3, 5, and 6 are included. 1 has been added to the vhsetup.sh too. I will consider the object cache in the future, too many things need to be modified, so I will leave this part on ls-cloud-image for now. 
Items 7 & 8 are not doable, since the current design is to let users complete the final installation from the browser. We can not install any plugin before it. 
Feel free to give it a try and let me know if you have any questions.
