### ISSUE TITLE
script doesn't install memcached package

### ISSUE THREAD

**Issue by K-E-N-W-A-Y** [litespeedtech/ols1clk#69]
script only install memcached php extension and it doesn't install memcached package. 

![Screenshot 2023-09-02 180030](https://github.com/litespeedtech/ols1clk/assets/25846872/bc4d3394-9dd8-4b29-8baf-0bdf61a16983)

![Screenshot 2023-09-02 180200](https://github.com/litespeedtech/ols1clk/assets/25846872/45ec0a14-149b-4340-b38a-1758bd9a85fe)

it can be simply fixed by manually installing and enabling memcached package 

```
yum install memcached -y

systemctl start memcached

systemctl enable memcached
```

![Screenshot 2023-09-02 180302](https://github.com/litespeedtech/ols1clk/assets/25846872/af6a782d-7e7f-4784-80a5-2b9b3a97c239)

![image](https://github.com/litespeedtech/ols1clk/assets/25846872/3eb5d032-937c-456f-b8db-c7bfd1e6a97d)

**Comment by K-E-N-W-A-Y** [comment]
i also noticed another strange behavior (maybe i did something wrong way)

first i installed wordpress to a custom path using this command

`bash <( curl -sk https://raw.githubusercontent.com/litespeedtech/ols1clk/master/ols1clk.sh ) --wordpressplus mydomain.com --wordpresspath '/var/www/www.mydomain.com' --lsphp 81`

then i installed LE using this.

```
sudo yum install certbot -y

/bin/bash <( curl -sk https://raw.githubusercontent.com/litespeedtech/ls-cloud-image/master/Setup/vhsetup.sh ) -d www.mydomain.com -le admin@mydomain.com -f
```

it issued SSL successfully but it didn't update **Web Admin → Configuration → Listeners → wordpressssl** correctly

i had to manually add these to **Listener wordpressssl > SSL > SSL Private Key & Certificate**

Private Key File: `/etc/letsencrypt/live/www.mydomain.com/privkey.pem`
Certificate File: `/etc/letsencrypt/live/www.mydomain.com/fullchain.pem`
Chained Certificate: `yes`

![image](https://github.com/litespeedtech/ols1clk/assets/25846872/e53974d8-ac0b-40dd-a5e5-88702069507b)


also i had to add `www.mydomain.com` to **Listener wordpressssl > General > Virtual Host Mappings**. it only had `mydomain.com` without www by default.

![image](https://github.com/litespeedtech/ols1clk/assets/25846872/2f2e9a38-70ad-4ce1-ae9b-9f0af29ab08e)

then site started working correctly with SSL.

![image](https://github.com/litespeedtech/ols1clk/assets/25846872/5b97d534-85e5-405a-8281-030e57d31808)

**Comment by Code-Egg** [comment]
Hi @K-E-N-W-A-Y 
To answer your question. 
1. Please consider using [this script](https://github.com/litespeedtech/ls-cloud-image/wiki/Build-WordPress-Image#what-if-i-want-to-use-it-directly), which covers the object cache and config unix socket for you. [Read more ](https://docs.litespeedtech.com/cloud/images/wordpress/)
2. The vhost script will auto-apply the certificate and set it at the virtual host level, you don't need to manually update it on the listener level. [More](https://docs.openlitespeed.org/configuration#set-up-ssl-for-virtual-hosts)
3. The current `--wordpressplus` option does not cover both the root domain and the www domain automatically. If you want to have www covered, please install OLS without WordPress, then use the vhost script to create the domain and WordPress for you, this way should cover both the root domain and www domain for you. You can also use [this script](https://github.com/litespeedtech/ls-cloud-image/wiki/Build-WordPress-Image#what-if-i-want-to-use-it-directly), which will add both the root domain and www domain for you.

**Comment by K-E-N-W-A-Y** [comment]
1. i'll check that but if you can please consider adding memcached package to install list. if script already install memcached php extension why not install memcached package to make it complete :D 

2, ah. i didn't touch vHost trying to fix it. just checked it to confirm it's empty. 

![image](https://github.com/litespeedtech/ols1clk/assets/25846872/e28bc233-4b40-4c35-a98f-994fa21eb2d4)

3. i see, after i ran LE script website link started to give me 403s. adding www domain fixed it. BTW i only use non www domain.

thanks

**Comment by Code-Egg** [comment]
For 2, i didn't touch vHost trying to fix it. just checked it to confirm it's empty. I checked the script, you should see a warning like sed: can't read xxxx/vhconf: No such file or directory. Because you did not use the vhost script to generate the vhconf, so it may look into the wrong path, and that's why it did not set the SSL certificate path for you. 

It will be too heavy if we have object cache services installed by default. Feel free to try [this script](https://github.com/litespeedtech/ls-cloud-image/wiki/Build-WordPress-Image#what-if-i-want-to-use-it-directly) in the future, it has both Memcached and Redis installed and pre-configured, so you can switch in between.
