### ISSUE TITLE
 lsphp56-mysqlnd &  lsphp70-json by default

### ISSUE THREAD

**Issue by dugi-x** [litespeedtech/ols1clk#7]
Is there any reason why not add `lsphp56-mysqlnd` to php56 by default
And `lsphp70-json` to php70 by default?

**Comment by Code-Egg** [comment]
Thanks, I would add lsphp56-mysqlnd but not sure about json, only if it is needed for default wordpress. The script tries to be lightweight making it so you can be up and running with wordpress with minimum packages. You can always install other packages themselves for specific scenarios.
