### ISSUE TITLE
Forcing HTTPS rule, breaks Let's Encrypt

### ISSUE THREAD

**Issue by peixotorms** [litespeedtech/ols1clk#71]
Hi,

When installing with letsencrypt, the scripts adds this to .htaccess:

```
### Forcing HTTPS rule start
RewriteEngine On
RewriteCond %{SERVER_PORT} 80
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
### Forcing HTTPS rule end
```

This will prevent letsencrypt from renewing the certificates, as it needs to validate it via http (by default).
Instead, you should use:

```
### Forcing HTTPS rule start
RewriteEngine On
RewriteCond %{SERVER_PORT} ^80$
RewriteCond %{REQUEST_URI} !^/\.well\-known/acme\-challenge/
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
### Forcing HTTPS rule end
```

Also, maybe instead of editing the htaccess, it could go under
Virtual Host > Rewrite

**Comment by Code-Egg** [comment]
Hi @peixotorms 

The force https rewrite rules will only be applied when you add a `-f`, `-F`, or `--force-https` option with the vhsetup.sh script. 
Thanks for the tip, but my site's cert renewal seems to be working fine with HTTPS redirect. Did you hit any cert renewal issues?

**Comment by peixotorms** [comment]
https://letsencrypt.org/docs/challenge-types/
With HTTP-01 challenge it calls http://<YOUR_DOMAIN>/.well-known/acme-challenge/<TOKEN>
so http needs to be "available" on that endpoint.

If you are renewing certificates automatically, when the certificate is due, it will send an http request.
If you have http to https globally, without the exclusion (ie when you set this on cloudflare for example), it fails to renew the certificates.

I have experienced this on hundreds of sites, as I am a developer.
The only option to allow it to renew, is to remove the redirect for that endpoint.

From letsencrypt:

> Our implementation of the HTTP-01 challenge follows redirects, up to 10 redirects deep. It only accepts redirects to “http:” or “https:”, and only to ports 80 or 443. It does not accept redirects to IP addresses. When redirected to an HTTPS URL, it does not validate certificates (since this challenge is intended to bootstrap valid certificates, it may encounter self-signed or expired certificates along the way).
> 
> The HTTP-01 challenge can only be done on port 80. Allowing clients to specify arbitrary ports would make the challenge less secure, and so it is not allowed by the ACME standard.

**Comment by Code-Egg** [comment]
Hi @peixotorms, 

I tried to launch a site LE and force the HTTPS rule applied, and then tried the dry run to renew the cert and it works, that's why I closed it. 

Now, I checked OLS release log, it seems the skip rewrite processing for LE verification req has been a built-in feature since 1.6.6, that's why I did not hit this issue.
