### ISSUE TITLE
can i upgrade php version

### ISSUE THREAD

**Issue by ParallaxCoder** [litespeedtech/ols1clk#73]
hi, can i use ols1clk to upgrade PHP version of existing WordPress installation?

from PHP 8.0 -> PHP 8.1

p.s. I used ols1clk to install openlitespeed + PHP 8.0 + wordpress (custom path). now i want to upgrade

thanks :)

**Comment by Code-Egg** [comment]
Hi @ParallaxCoder ,

Please follow this guide https://docs.litespeedtech.com/cloud/images/wordpress/#how-do-i-use-lsphp81

**Comment by ParallaxCoder** [comment]
thank you
