### ISSUE TITLE
Ubuntu 24.04

### ISSUE THREAD

**Issue by StefanoMarchesi** [litespeedtech/ols1clk#74]
Please add compatibiliy for the last ubuntu lts releasse

**Comment by Code-Egg** [comment]
Hi, the [latest commit](https://github.com/litespeedtech/ols1clk/commit/b52becfad68754529a0958f53593e71f37dc0ca1) should have Ubuntu 24.04 covered, feel free to give it a try.

**Comment by StefanoMarchesi** [comment]
I'm sorry but seems not resolved:

Start OpenLiteSpeed one click installation >> >> >> >> >> >> >>
System update
List Restart services only
Start setup OpenLiteSpeed
     - add litespeedtech repo
     - update list
     - Install OpenLiteSpeed
An error occured during OpenLiteSpeed installation.
     - Install lsphp83
End setup OpenLiteSpeed
ols1clk.sh: line 1659: /usr/local/lsws/admin/fcgi-bin/admin_php: No such file or directory
mv: cannot move 'example.key' to '/usr/local/lsws/conf/example.key': No such file or directory
mv: cannot move 'example.crt' to '/usr/local/lsws/conf/example.crt': No such file or directory
chmod: cannot access '/usr/local/lsws/conf/example.key': No such file or directory
chmod: cannot access '/usr/local/lsws/conf/example.crt': No such file or directory
Install wp_cli
Start setup virtual host config
/usr/local/lsws/conf/httpd_config.conf is missing. It appears that something went wrong during OpenLiteSpeed installation.
End setup virtual host config
Avoid port 80/443 conflict.
Start Install MariaDB
     - Install software properties
     - Add MariaDB repo
     - Update packages
     - Install MariaDB
     - Start MariaDB
     - Set MariaDB root
End Install MariaDB
Start setup MariaDB
Finished MySQL setup without error.
End setup mysql
Start Download WordPress file
End Download WordPress file
Start Create Wordpress config
Done Create Wordpress config
Install Postfix
     - Config OpenLiteSpeed
sed: can't read /usr/local/lsws/conf/httpd_config.conf: No such file or directory
     - Config php.ini
Failed to start lsws.service: Unit lsws.service not found.
Installation finished. Some errors seem to have occured, please check this as you may need to manually fix them.
Please access http://server_IP:80/ to finish setting up your WordPress site.
Also, you may want to activate the LiteSpeed Cache plugin to get better performance.
End OpenLiteSpeed one click installation << << << << << << <<

Start auto testing >> >> >> >>
Error: test webAdmin page failed.
Error: test Example vhost page failed.
Error: test wordpress HTTP first page failed.
Error: test wordpress HTTPS first page failed.
Errors were encountered during testing. In many cases these errors can be solved manually by referring to installation logs.
Service loading issues can sometimes be resolved by performing a restart of the web server.
Reinstalling the web server can also help if neither of the above approaches resolve the issue.
End auto testing << << << <<
Thanks for using OpenLiteSpeed One click installation!

**Comment by Code-Egg** [comment]
@StefanoMarchesi 
It seems I don't have such an issue, may I know the commend you ran on the server
`bash <( curl -k https://raw.githubusercontent.com/litespeedtech/ols1clk/master/ols1clk.sh ) --lsphp 83`
![image](https://github.com/litespeedtech/ols1clk/assets/17311438/944a0f06-1b12-4acf-94cb-873205714f1c)
